/**
 * MyCertificate.c
 * Placeholder certificate for source control.
 *
 * Replace this file locally with your real certificate generated by MyScript.
 * Do NOT commit real certificate bytes.
 */

#include <stddef.h>

#ifndef VO_CERTIFICATE_TYPE
#define VO_CERTIFICATE_TYPE

typedef struct _voCertificate
{
  const char* bytes;
  size_t length;
}
voCertificate;

#endif // VO_CERTIFICATE_TYPE

static const char myCertificate_BYTES[] =
{
  0
};

voCertificate const myCertificate =
{
  myCertificate_BYTES,
  0
};
